import { useState } from 'react';
import { ExternalLink, Github, Folder, X, Gamepad2, Box, Bird, Blocks, PenTool, Car, Route, FileText, Rocket, Users, Stethoscope, Youtube, Image, Smartphone, Plus } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import SpaceInvadersGame from './SpaceInvadersGame';
import TicTacToeGame from './TicTacToeGame';
import BrickBreakerGame from './BrickBreakerGame';
import TrafficRiderGame from './TrafficRiderGame';
import PathfinderGame from './PathfinderGame';

// ---------------------------------------------------------------------------
// STATIC PROJECT DATA — snapshot from GitHub on 2026-03-06
// To refresh: a "Refresh Projects" button will be added before launch.
// ---------------------------------------------------------------------------
const GITHUB_USERNAME = 'vatsal-agra';

const projects = [
  // ---- FEATURED ----
  {
    title: 'Space Invaders',
    repoName: 'space-invaders-pygame',
    description: 'Feature-complete Space Invaders arcade game — multi-level progression, coin economy, speed upgrades, and full sound effects built with Python and Pygame.',
    tech: ['Python', 'Pygame'],
    github: 'https://github.com/vatsal-agra/space-invaders-pygame',
    demo: '',
    featured: true,
    icon: Rocket,
    playable: true,
    thumbnail: '/portfolio thumbnails/p_01_space_invaders.png',
    readme: `# Space Invaders

A fully featured Space Invaders arcade game built from scratch in Python — complete with a home screen, multiple levels, a coin economy, and an in-game shop.

## Features

- **Home Screen** — level display, enemy count, and upgrade shop before each round
- **Multiple Levels** — enemies increase in number and speed as you progress
- **Coin Economy** — earn coins by defeating enemies, spend them on upgrades
- **2x Bullet Speed Upgrade** — purchasable in the shop for 650 coins
- **Sound Effects** — shooting, explosion, and background music
- **Score & Target Tracking** — live score and target display during gameplay
- **Game Over & Win States** — full end-game screens

## Tech Stack

- Python
- Pygame — game engine, rendering, input handling, sound
- Pygame Mixer — audio playback

## How to Run
\`\`\`
pip install pygame
python space-invaders-final-game.py
\`\`\`

## Key Concepts Demonstrated
- Game loop architecture
- Collision detection using Euclidean distance
- Sprite and asset management
- Multi-level progression logic
- Coin economy and in-game purchasing system
- Sound integration with Pygame Mixer`,
  },
  {
    title: 'ThumbnailPro AI',
    repoName: 'thumbnailpro-ai',
    description: 'High-CTR YouTube Thumbnails, Generated by Gemini AI. A professional-grade SaaS that uses Google Gemini Vision to analyse video content and generate thumbnails.',
    tech: ['React', 'TypeScript', 'Gemini AI', 'SaaS'],
    github: 'https://github.com/vatsal-agra/thumbnailpro-ai',
    demo: '',
    featured: true,
    icon: Image,
    playable: false,
    thumbnail: '/portfolio thumbnails/p_02_thumbnailpro.png',
    readme: `# 🎬 ThumbnailPro AI

**High-CTR YouTube Thumbnails, Generated by Gemini AI.**

ThumbnailPro AI is a professional-grade SaaS application that leverages Google's state-of-the-art **Gemini Vision** models to analyze video content and generate high-converting thumbnails in seconds.

## ✨ Key Features

### 🧠 Intelligent Video Analysis
Simply paste a YouTube URL. Our engine scans the metadata and frames to understand the core narrative, ensuring your thumbnails are contextually perfect.

### 🎭 Multiple Aspect Ratios
Generate thumbnails in both **16:9 (landscape)** and **9:16 (portrait/Shorts)** formats simultaneously.

### ⚡ Instant Generation
No waiting — thumbnails are generated and ready to download in seconds.

## Tech Stack
- React + TypeScript + Vite
- Google Gemini Vision API
- Tailwind CSS
- Netlify (deployment)`,
  },
  {
    title: 'MockMate',
    repoName: 'MockMate',
    description: 'AI-powered mobile interview prep app combining Gemini 2.5 Flash for linguistic analysis and Google ML Kit for real-time behavioral tracking.',
    tech: ['Flutter', 'Gemini AI', 'ML Kit', 'Mobile'],
    github: 'https://github.com/vatsal-agra/MockMate',
    demo: '',
    featured: true,
    icon: Smartphone,
    playable: false,
    thumbnail: '/portfolio thumbnails/p_03_mockmate.png',
    readme: `# MockMate 🎯
### Master Your Interview Skills with AI-Powered Intelligence

**MockMate** is a cutting-edge mobile application designed to bridge the gap between candidate preparation and real-world interview success. By combining **Google Gemini 2.5 Flash** for deep linguistic analysis and **Google ML Kit** for real-time behavioral tracking, MockMate provides a comprehensive, 360-degree feedback loop for any role you're targeting.

## 🚀 Key Features

### 1. Hybrid Intelligence Engine 🧠
- Real-time speech analysis powered by Gemini 2.5 Flash
- ML Kit face and body language tracking
- Sentiment and confidence scoring

### 2. Role-Specific Question Banks
- Questions tailored to specific job roles and experience levels
- Curated from real interview experiences

### 3. Detailed Performance Reports
- Transcript with annotated feedback
- Confidence, clarity, and relevance scores
- Actionable improvement suggestions

## Tech Stack
- Flutter (cross-platform mobile)
- Google Gemini 2.5 Flash API
- Google ML Kit
- Firebase`,
  },
  {
    title: 'Medical Prescription OCR SaaS',
    repoName: 'medical-prescription-ocr-saas',
    description: 'A deployed SaaS tool that allows doctors to upload multiple patient prescriptions and automatically generates a consolidated clinical summary using OCR and AI.',
    tech: ['Python', 'OCR', 'LangChain', 'AI', 'SaaS'],
    github: 'https://github.com/vatsal-agra/medical-prescription-ocr-saas',
    demo: '',
    featured: true,
    icon: Stethoscope,
    playable: false,
    thumbnail: '/portfolio thumbnails/p_04_medical_ocr.png',
    readme: `# Medical Prescription OCR SaaS

A deployed SaaS tool that allows doctors to upload multiple patient prescriptions and automatically generates a consolidated clinical summary — saving time and reducing manual record review.

## What It Does

Doctors frequently need to review a patient's prescription history across multiple visits and providers. This tool streamlines that process:

1. **Upload** — doctor uploads multiple prescription documents (images or PDFs)
2. **OCR Extraction** — the system extracts raw text from each document using OCR
3. **AI Summary** — a language model consolidates the extracted text into a structured clinical summary
4. **Download** — the doctor receives a clean, ready-to-use summary report

## Tech Stack
- Python + Flask
- Tesseract OCR / Google Vision API
- LangChain + OpenAI / Gemini
- Deployed on cloud infrastructure`,
  },
  {
    title: 'Autonomous Content Pipeline',
    repoName: 'autonomous-content-pipeline',
    description: 'A fully automated, zero-touch AI content pipeline that runs daily — selecting videos, generating taglines with AI, embedding them, and publishing to YouTube.',
    tech: ['n8n', 'Python', 'YouTube API', 'AI Automation'],
    github: 'https://github.com/vatsal-agra/autonomous-content-pipeline',
    demo: '',
    featured: true,
    icon: Youtube,
    playable: false,
    thumbnail: '/portfolio thumbnails/p_05_pipeline.png',
    readme: `# Autonomous AI Content Pipeline

A fully automated, zero-touch AI content pipeline that runs daily — selecting videos and titles from a Google Sheet, generating contextual taglines using AI, embedding them onto the video, and publishing to YouTube without any human intervention.

## What It Does

Once deployed, this pipeline runs on a daily schedule and autonomously handles the entire content creation and distribution workflow:

1. **Data Fetch** — reads a list of video titles and pre-provided video files from a Google Sheet
2. **AI Tagline Generation** — sends each title to an AI model to generate a punchy, platform-optimised tagline
3. **Video Rendering** — embeds the generated tagline as a text overlay onto the video using FFmpeg
4. **YouTube Upload** — publishes the finalised video to YouTube with metadata, tags, and scheduling

## Tech Stack
- n8n (workflow orchestration)
- Python + FFmpeg (video processing)
- Google Sheets API
- YouTube Data API v3
- OpenAI / Gemini (tagline generation)`,
  },
  {
    title: 'Flappy Bird AI',
    repoName: 'flappy-bird-ai',
    description: 'A self-learning AI agent that masters Flappy Bird through neuroevolution (NEAT) — achieving perfect, never-ending play with no hardcoded rules.',
    tech: ['Python', 'Pygame', 'NEAT-Python', 'Neural Networks'],
    github: 'https://github.com/vatsal-agra/flappy-bird-ai',
    demo: '',
    featured: true,
    icon: Bird,
    playable: false,
    thumbnail: '/portfolio thumbnails/p_06_flappy_ai.png',
    readme: `# Flappy Bird AI — Self-Learning Agent using NEAT

A self-learning AI agent that masters Flappy Bird through neuroevolution — achieving perfect, never-ending play with no hardcoded rules or strategies.

## How It Works

The agent uses the **NEAT (NeuroEvolution of Augmenting Topologies)** algorithm to evolve a population of neural networks across generations. Each bird in a generation is controlled by its own neural network. Birds that survive longer are rewarded with higher fitness scores, and the best-performing networks are selected to produce the next generation.

## Features
- Population of AI birds trained simultaneously
- Neural networks evolve over generations
- Real-time generation and score display
- No hardcoded jump logic — entirely learned behaviour

## Tech Stack
- Python + Pygame
- NEAT-Python (neuroevolution library)

## How to Run
\`\`\`
pip install pygame neat-python
python flappy-bird-neat.py
\`\`\``,
  },
  {
    title: 'A* Pathfinder Visualiser',
    repoName: 'astar-pathfinding-visualiser',
    description: 'Interactive real-time visualisation of the A* search algorithm — place a start, end, and barriers on a grid, then watch A* find the shortest path step by step.',
    tech: ['Python', 'Pygame', 'Algorithms'],
    github: 'https://github.com/vatsal-agra/astar-pathfinding-visualiser',
    demo: '',
    featured: true,
    icon: Route,
    playable: true,
    thumbnail: '/portfolio thumbnails/p_07_astar.png',
    readme: `# A* Pathfinding Visualiser

An interactive real-time visualisation of the A* search algorithm — place a start, an end, and barriers on a grid, then watch A* find the shortest path step by step.

## What It Does

You build a grid scenario by placing a start node, an end node, and barrier nodes. Once triggered, the A* algorithm runs visually — showing open nodes (green), closed/explored nodes (red), and the final shortest path (purple) once found.

## How A* Works

A* is a best-first search algorithm that combines the actual distance from the start (g-cost) with an estimated distance to the goal (h-cost, the heuristic). This makes it significantly faster than algorithms like Dijkstra's in most practical grid scenarios.

## Controls
- **Left click** — place start, then end, then barriers
- **Right click** — remove a node
- **Spacebar** — run the algorithm
- **C** — clear the grid

## Tech Stack
- Python + Pygame`,
  },
  {
    title: '3D Obstacle Course (Obby)',
    repoName: '3d-obstacle-course-ursina',
    description: 'First-person 3D obstacle course game with 4 progressive levels, hidden trigger blocks, decoy mechanics, and full in-game UI. Built with Python and Ursina.',
    tech: ['Python', 'Ursina', '3D Engine', 'Game Dev'],
    github: 'https://github.com/vatsal-agra/3d-obstacle-course-ursina',
    demo: '',
    featured: true,
    icon: Box,
    playable: false,
    thumbnail: '/portfolio thumbnails/p_08_obby.png',
    readme: `# 3D Obstacle Course Game (Obby)

A first-person 3D obstacle course game built in Python using the Ursina engine — featuring four progressively harder levels, hidden trigger blocks, fake decoy blocks, and a full in-game UI.

## Gameplay

You start on a small platform surrounded by white blocks — some are decoys, one is a hidden trigger. Find and click the trigger block to reveal the first obstacle course. Navigate the floating platforms to reach the next base, find the trigger there, and unlock the next level.

## Features
- 4 progressively harder levels
- Hidden trigger blocks with fake decoys
- First-person movement and camera
- Full in-game UI (level display, instructions)
- Win screen on completion

## Tech Stack
- Python
- Ursina Engine (3D game framework)

## How to Run
\`\`\`
pip install ursina
python obby_game.py
\`\`\``,
  },

  // ---- NON-FEATURED ----
  {
    title: 'Hangman',
    repoName: 'hangman-python',
    description: 'Two-player Hangman using Python Turtle for drawing and Tkinter for UI — hidden word entry, hint system, and progressive hangman figure drawn on wrong guesses.',
    tech: ['Python', 'Turtle', 'Tkinter'],
    github: 'https://github.com/vatsal-agra/hangman-python',
    demo: '',
    featured: false,
    icon: PenTool,
    playable: false,
    thumbnail: '/portfolio thumbnails/p_09_hangman.png',
    readme: `# Hangman

A classic Hangman game with a twist — built using Python's Turtle graphics for the drawing and Tkinter for the UI. One player secretly enters a word, the other guesses letters one at a time, with a limited hint system and a progressively drawn hangman figure tracking wrong guesses.

## How It Works

1. Player 1 enters a secret word (hidden behind \`?\` characters as they type)
2. A Turtle window opens showing blank dashes for each letter
3. Player 2 guesses one letter at a time
4. Correct guesses reveal the letter; wrong guesses add a body part to the hangman drawing
5. Player 2 can use hints (limited) to reveal a letter

## Features
- Two-player local gameplay
- Turtle-drawn hangman figure (progressive on wrong guesses)
- Tkinter-based letter input UI
- Hint system with limited uses
- Win/loss detection

## Tech Stack
- Python + Turtle (drawing)
- Tkinter (UI)`,
  },
  {
    title: 'Dijkstra Pathfinding Visualiser',
    repoName: 'dijkstra-pathfinding-visualiser',
    description: 'Interactive real-time visualisation of Dijkstra\'s algorithm — place source and destinations on a grid, watch pathfinding live, with full distance breakdown.',
    tech: ['Python', 'Tkinter', 'Algorithms'],
    github: 'https://github.com/vatsal-agra/dijkstra-pathfinding-visualiser',
    demo: '',
    featured: false,
    icon: Route,
    playable: false,
    thumbnail: '/portfolio thumbnails/p_10_dijkstra.png',
    readme: `# Dijkstra Pathfinding Visualiser

An interactive visualisation of Dijkstra's shortest path algorithm — select a source and multiple destinations on a grid, watch the algorithm explore in real time, and get a clean breakdown of the shortest distance to every destination.

## What It Does

You place a source node and one or more destination nodes on a 15x15 grid. Dijkstra's algorithm then runs visually — showing explored nodes in yellow and the shortest paths in red. Once complete, a separate window displays the shortest distance from the source to each destination.

## Features
- 15×15 interactive grid
- Visual exploration (yellow = visited, red = shortest path)
- Multiple destination support
- Distance breakdown popup on completion
- Clear and reset controls

## Tech Stack
- Python + Tkinter

## Controls
- **Left click** — place source (first click), then destinations
- **Right click** — remove a node
- **Enter** — run Dijkstra's algorithm`,
  },
  {
    title: 'Brick Breaker Game',
    repoName: 'brick-breaker-game',
    description: 'Classic breakout-style arcade game with colorful bricks, paddle physics, and progressive difficulty.',
    tech: ['Python', 'Pygame'],
    github: 'https://github.com/vatsal-agra/brick-breaker-game',
    demo: '',
    featured: false,
    icon: Blocks,
    playable: true,
    thumbnail: '/portfolio thumbnails/p_11_brickbreaker.png',
    readme: `# Brick Breaker Game

A retro-style Brick Breaker arcade game built with Python and Pygame, featuring colorful rows of bricks, smooth paddle controls, and progressive difficulty.

## Features
- Three rows of colored bricks (red, yellow, green)
- Smooth paddle control (mouse or keyboard)
- Ball physics with angle-based collision detection
- Score tracking
- Level completion screen

## Tech Stack
- Python + Pygame`,
  },
  {
    title: 'Traffic Rider Game',
    repoName: 'traffic-rider-game',
    description: 'Fast-paced top-down car racing game where you dodge oncoming traffic and cover as much distance as possible.',
    tech: ['Python', 'Pygame'],
    github: 'https://github.com/vatsal-agra/traffic-rider-game',
    demo: '',
    featured: false,
    icon: Car,
    playable: true,
    thumbnail: '/portfolio thumbnails/p_12_trafficrider.png',
    readme: `# Traffic Rider Game

A fast-paced top-down car racing game built with Python and Pygame. Dodge oncoming traffic and survive as long as possible while your distance meter climbs.

## Features
- Top-down perspective gameplay
- Random oncoming traffic generation
- Collision detection
- Distance meter
- Increasing speed over time

## Tech Stack
- Python + Pygame`,
  },
  {
    title: 'Modern Tic Tac Toe',
    repoName: 'modern-tic-tac-toe',
    description: 'Beautifully designed two-player Tic Tac Toe with persistent score tracking across rounds.',
    tech: ['Python', 'Tkinter'],
    github: 'https://github.com/vatsal-agra/modern-tic-tac-toe',
    demo: '',
    featured: false,
    icon: Gamepad2,
    playable: false,
    thumbnail: '/portfolio thumbnails/p_13_tictactoe.png',
    readme: `# Modern Tic Tac Toe

A clean, modern implementation of the classic two-player Tic Tac Toe game, built with Python and Tkinter.

## Features
- Two-player local gameplay (X vs O)
- Persistent score tracking across rounds
- Win detection for all rows, columns, and diagonals
- Draw detection
- Reset and new game buttons
- Minimal, elegant design

## Tech Stack
- Python + Tkinter`,
  },
];


type Project = typeof projects[0];

const getProjectImage = (project: { thumbnail?: string; repoName: string }) =>
  project.thumbnail || `https://opengraph.githubassets.com/1/${GITHUB_USERNAME}/${project.repoName}`;

const ProjectsSection = () => {
  const [filter, setFilter] = useState<'all' | 'featured'>('featured');
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);
  const [isPlaying, setIsPlaying] = useState(false);

  const filteredProjects = filter === 'all'
    ? projects
    : projects.filter(p => p.featured);

  return (
    <section className="min-h-screen py-24">
      <div className="container mx-auto px-6">
        <div className="text-center mb-8 animate-fade-in">
          <span className="text-primary font-mono text-sm">{'// Projects'}</span>
          <h2 className="text-3xl md:text-5xl font-bold mt-2">
            What I've <span className="text-gradient">Built</span>
          </h2>
          <p className="text-zinc-500 mt-4 max-w-2xl mx-auto">
            A showcase of my public GitHub projects. Click any card to read the full documentation.
          </p>
        </div>

        <div className="flex justify-center gap-4 mb-8 animate-fade-in" style={{ animationDelay: '0.2s' }}>
          {(['featured', 'all'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setFilter(tab)}
              className={`px-5 py-2 rounded-full text-sm font-medium transition-all duration-300 ${
                filter === tab
                  ? 'bg-primary text-primary-foreground'
                  : 'glass text-muted-foreground hover:text-foreground'
              }`}
            >
              {tab.charAt(0).toUpperCase() + tab.slice(1)}
            </button>
          ))}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredProjects.map((project) => (
            <div
              key={project.repoName}
              onClick={() => { setSelectedProject(project); setIsPlaying(false); }}
              className="bg-[#18181b] rounded-xl overflow-hidden border border-zinc-800 hover:border-zinc-700 transition-colors cursor-pointer flex flex-col h-full group"
            >
              <div className="h-48 bg-zinc-900 relative overflow-hidden">
                <img
                  src={getProjectImage(project)}
                  alt={project.title}
                  className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
                  onError={(e) => { (e.target as HTMLImageElement).src = '/placeholder.svg'; }}
                />
                <div className="absolute inset-0 bg-black/10 group-hover:bg-black/0 transition-colors" />
                <div className="absolute top-3 right-3">
                  <a
                    href={project.github}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="bg-black/80 backdrop-blur-sm text-white p-2 rounded-full hover:bg-white hover:text-black transition-all border border-white/10 block"
                    onClick={e => e.stopPropagation()}
                  >
                    <Github size={16} />
                  </a>
                </div>
                {project.featured && (
                  <div className="absolute bottom-3 left-3">
                    <span className="text-[9px] font-bold uppercase tracking-widest bg-primary/90 backdrop-blur-sm text-black px-2 py-0.5 rounded">
                      Featured
                    </span>
                  </div>
                )}
              </div>

              <div className="p-6 flex-1 flex flex-col">
                <div className="flex items-center justify-between mb-3">
                  <project.icon className="w-6 h-6 text-primary" />
                  {project.playable && (
                    <span className="text-[10px] uppercase tracking-wider text-green-400 font-bold flex items-center gap-1">
                      <span className="w-1.5 h-1.5 rounded-full bg-green-400 inline-block" />
                      Playable
                    </span>
                  )}
                </div>

                <h3 className="text-xl font-bold mb-2 group-hover:text-primary transition-colors">{project.title}</h3>
                <p className="text-zinc-400 text-sm line-clamp-3 mb-4 flex-1">{project.description}</p>

                <div className="flex flex-wrap gap-1.5 mt-auto pt-4 border-t border-zinc-800/50">
                  {project.tech.slice(0, 4).map((tech, i) => (
                    <span key={i} className="text-[10px] font-mono bg-zinc-900 border border-zinc-800 text-zinc-400 px-2 py-0.5 rounded">
                      {tech}
                    </span>
                  ))}
                  {project.tech.length > 4 && (
                    <span className="text-[10px] font-mono text-zinc-500 px-1 py-0.5">+{project.tech.length - 4}</span>
                  )}
                </div>
              </div>
            </div>
          ))}
          {filter === 'featured' && (
            <div
              onClick={() => setFilter('all')}
              className="bg-zinc-900/50 rounded-xl border border-zinc-800 border-dashed hover:border-primary/50 transition-all cursor-pointer flex flex-col items-center justify-center p-8 group min-h-[350px]"
            >
              <div className="w-16 h-16 rounded-full bg-zinc-800 flex items-center justify-center group-hover:bg-primary/20 transition-colors mb-4">
                <Plus className="w-8 h-8 text-zinc-400 group-hover:text-primary transition-colors" />
              </div>
              <h3 className="text-xl font-bold group-hover:text-primary transition-colors text-center">See All Projects</h3>
              <p className="text-zinc-500 text-sm text-center mt-2 group-hover:text-zinc-400">
                Explore the complete technical portfolio
              </p>
            </div>
          )}
        </div>

        <Dialog open={!!selectedProject} onOpenChange={(open) => {
          if (!open) { setSelectedProject(null); setIsPlaying(false); }
        }}>
          <DialogContent className={`bg-[#18181b] border-zinc-800 ${isPlaying ? 'max-w-4xl' : 'max-w-4xl'} max-h-[90vh] overflow-y-auto p-0`}>
            {selectedProject && isPlaying ? (
              <div className="flex items-center justify-center bg-black min-h-[600px] w-full">
                {selectedProject.title === 'Space Invaders' && <SpaceInvadersGame onClose={() => setIsPlaying(false)} />}
                {selectedProject.title === 'Brick Breaker Game' && <BrickBreakerGame onClose={() => setIsPlaying(false)} />}
                {selectedProject.title === 'Traffic Rider Game' && <TrafficRiderGame onClose={() => setIsPlaying(false)} />}
                {selectedProject.title === 'Modern Tic Tac Toe' && <TicTacToeGame onClose={() => setIsPlaying(false)} />}
                {selectedProject.title === 'A* Pathfinder Visualiser' && <PathfinderGame onClose={() => setIsPlaying(false)} />}
              </div>
            ) : selectedProject && (
              <>
                <div className="h-64 bg-zinc-900 relative flex-shrink-0">
                  <img
                    src={getProjectImage(selectedProject)}
                    alt={selectedProject.title}
                    className="w-full h-full object-cover object-top"
                    onError={(e) => { (e.target as HTMLImageElement).src = '/placeholder.svg'; }}
                  />
                  <button
                    onClick={() => setSelectedProject(null)}
                    className="absolute top-4 right-4 bg-black/70 text-white p-2 rounded-full hover:bg-black transition-colors border border-white/10"
                  >
                    <X size={20} />
                  </button>
                </div>

                <div className="p-8">
                  <DialogHeader>
                    <DialogTitle className="text-3xl font-bold">{selectedProject.title}</DialogTitle>
                    <p className="text-zinc-400 mt-1">{selectedProject.description}</p>
                  </DialogHeader>

                  <div className="mt-8 grid grid-cols-1 lg:grid-cols-3 gap-8">
                    {/* README Panel */}
                    <div className="lg:col-span-2">
                      <h4 className="text-zinc-100 flex items-center text-base font-semibold mb-4 border-b border-zinc-800 pb-2">
                        <FileText size={18} className="mr-2 text-primary" />
                        Project Documentation
                      </h4>
                      {selectedProject.readme ? (
                        <div className="bg-zinc-900/20 p-6 rounded-xl border border-zinc-800/30 text-zinc-300 leading-relaxed github-markdown text-sm">
                          <ReactMarkdown remarkPlugins={[remarkGfm]}>{selectedProject.readme}</ReactMarkdown>
                        </div>
                      ) : (
                        <div className="p-8 bg-zinc-900/30 rounded-xl border border-zinc-800/50 text-center">
                          <p className="text-zinc-500 italic text-sm">No README.md available for this repository.</p>
                        </div>
                      )}
                    </div>

                    {/* Sidebar */}
                    <div>
                      <div className="bg-zinc-900/40 p-6 rounded-2xl border border-zinc-800/50 space-y-6 sticky top-8">
                        <div className="space-y-3">
                          <h4 className="text-xs font-bold uppercase tracking-[0.2em] text-zinc-500 flex items-center">
                            <div className="w-1 h-3 bg-primary mr-2" />
                            Links
                          </h4>
                          <a
                            href={selectedProject.github}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center px-4 py-3 bg-white text-black font-bold rounded-xl hover:bg-primary hover:text-white transition-all text-sm w-full justify-center group"
                          >
                            <Github size={18} className="mr-2" />
                            View on GitHub
                          </a>
                          {selectedProject.playable && (
                            <button
                              onClick={() => setIsPlaying(true)}
                              className="inline-flex items-center px-4 py-3 bg-green-600 hover:bg-green-700 text-white font-bold rounded-xl transition-all text-sm w-full justify-center shadow-lg shadow-green-900/20"
                            >
                              <Gamepad2 size={18} className="mr-2" />
                              Launch Game
                            </button>
                          )}
                          {selectedProject.demo && (
                            <a
                              href={selectedProject.demo}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="inline-flex items-center px-4 py-3 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl transition-all text-sm w-full justify-center"
                            >
                              <ExternalLink size={18} className="mr-2" />
                              Live Demo
                            </a>
                          )}
                        </div>

                        <div className="space-y-3 pt-4 border-t border-zinc-800">
                          <h4 className="text-xs font-bold uppercase tracking-[0.2em] text-zinc-500 flex items-center">
                            <div className="w-1 h-3 bg-primary mr-2" />
                            Tech Stack
                          </h4>
                          <div className="flex flex-wrap gap-2">
                            {selectedProject.tech.map((tech, i) => (
                              <span key={i} className="text-[10px] font-mono bg-zinc-950 border border-zinc-800 text-zinc-400 px-3 py-1.5 rounded-lg uppercase tracking-wider font-semibold">
                                {tech}
                              </span>
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </>
            )}
          </DialogContent>
        </Dialog>
      </div>
    </section>
  );
};

export default ProjectsSection;
